name: AKS Auto Start
on:
  workflow_dispatch:
  # schedule:
    # Run everyday
    # - cron: '30 7 * * *' # Everyday at 7:30am UTC (Will enable after tested)
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install assert.sh
        run: git clone https://github.com/torokmark/assert.sh.git 
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
#       - name: AKS Auto Start
#         run: ./scripts/aks-auto-start.sh
      - name: Tests
        run: ./scripts/tests.sh
